### PR TITLE
Add docker support

### PR DESCRIPTION
**Pull request by cyberbit**
Here is a Dockerfile I got working, supporting `compose` and `run`. It launches the binary through `supervisor` to manage any unhandled crashes. The compose file points to my own published image at the moment (https://hub.docker.com/r/cyberbit/satpaper), but replacing `image: cyberbit/satpaper` with `build: .` allows building the image locally.

The final image from Docker Hub is around 30 MB compressed, or ~1.5 Satpaper cycles.

### CODE REVIEW

**Comment by Colonial-Dev** [comment]
I like the idea, but I just want to check something first - what's the maintenance burden on a Docker config? I'm pretty sure it's basically nothing, but Docker isn't really my forte and I want to know what I'm getting myself into :p 

Also, would it be possible to put everything into a `docker/` subdir? I have a bad feeling that people will skim the file list and think it *only* supports Docker or something :sweat_smile:

**Comment by cyberbit** [comment]
> what's the maintenance burden on a Docker config?

As you say, basically nothing. I have built this out as an [Alpine Linux](https://www.alpinelinux.org/) image, so as long as satpaper continues to support Linux it should Just Work™️. If it does require a `libfoo` in the future, it can be added to the Dockerfile trivially via `apk` at build time.

> would it be possible to put everything into a docker/ subdir?

Yes, I'll update the PR.

**Comment by cyberbit** [comment]
PR updated:

- Moved tooling to `docker/`
- Added `build-docker` to the Cargo Comprehensive action. This runs the minimum necessary for `cargo test --release` within Docker.

An automatic Docker Hub release can be done (https://docs.docker.com/build/ci/github-actions/push-multi-registries/) but if you don't want to do a Docker Hub account, I can keep my published fork updated to the best of my ability.

**Comment by Colonial-Dev** [comment]
Thanks for the contribution! And yeah, probably best for you to do the Docker Hub upkeep :p

**Pull request merged**
