### PR TITLE
Add Windows Support

### PR DESCRIPTION
**Pull request by Dan0xE**
This hacky PowerShell script implementation adds support for Windows.
Although the formatting of the script is ugly, please do NOT CHANGE the formatting of the script, otherwise the script will break!

(Also I just noticed that my code formatting rules might not adhere to the previous code formatting rules, I do apologize for that!)

I tested this on my Windows 11 and Windows 10 machine, and it seems to work fine :)

### CODE REVIEW

**Comment by Colonial-Dev** [comment]
Looks good to me - but I would add a comment warning that the script formatting is meaningful, because otherwise someone (i.e. probably me) is going to break it later :p

**Comment by Dan0xE** [comment]
> Looks good to me - but I would add a comment warning that the script formatting is meaningful, because otherwise someone (i.e. probably me) is going to break it later :p

done! :)

**Comment by Dan0xE** [comment]
Ah, just realized I made a small mistake in the commit message, The open issue is in the PowerShell repo, NOT in the vscode-powershell repo, it was just referenced [there](https://github.com/PowerShell/vscode-powershell/issues/977) and I overlooked that, Whoops

**Comment by Colonial-Dev** [comment]
Awesome, thanks for the contribution!

**Pull request merged**
